const TIMEFORMAT = {
  DDMMYYHHMMSS_BACKSLASH: 'DD/MM/YY HH.mm.ss',
  DDMMYYHHMM_BACKSLASH: 'DD/MM/YY HH.mm',
  DDMMMMYYYYHHMMSS: 'DD MMMM YYYY HH.mm.ss',
  DDMMMYYHHMM: 'DD MMM YY HH.mm',
};

export default TIMEFORMAT;
